//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVanHung_OnTap.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BanHoaEntityEntities : DbContext
    {
        public BanHoaEntityEntities()
            : base("name=BanHoaEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuDeHoa> ChuDeHoas { get; set; }
        public virtual DbSet<Hoa> Hoas { get; set; }
    
        public virtual ObjectResult<GetChuDeHoa_Result> GetChuDeHoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChuDeHoa_Result>("GetChuDeHoa");
        }
    
        public virtual ObjectResult<GetFlower_Result> GetFlower()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFlower_Result>("GetFlower");
        }
    
        public virtual int InsertFlower(string maHoa, string tenHoa, Nullable<double> giaBan, Nullable<int> soLuong, string hinhAnh, string maChuDe, ObjectParameter error)
        {
            var maHoaParameter = maHoa != null ?
                new ObjectParameter("MaHoa", maHoa) :
                new ObjectParameter("MaHoa", typeof(string));
    
            var tenHoaParameter = tenHoa != null ?
                new ObjectParameter("TenHoa", tenHoa) :
                new ObjectParameter("TenHoa", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(double));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var maChuDeParameter = maChuDe != null ?
                new ObjectParameter("MaChuDe", maChuDe) :
                new ObjectParameter("MaChuDe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertFlower", maHoaParameter, tenHoaParameter, giaBanParameter, soLuongParameter, hinhAnhParameter, maChuDeParameter, error);
        }
    }
}
