//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVanHung_OnTap.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuDeHoa
    {
        public ChuDeHoa()
        {
            this.Hoas = new HashSet<Hoa>();
        }
    
        public string MaChuDe { get; set; }
        public string LoaiChuDe { get; set; }
    
        public virtual ICollection<Hoa> Hoas { get; set; }
    }
}
